version: '2.4'
services:
  arl_pytorch:
    container_name: arl_pytorch
    image: arl:latest
    runtime: nvidia
    environment:
      QT_X11_NO_MITSHM: '1'
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
    network_mode: host
    privileged: true
    stdin_open: true
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - ../src:/workspace/src
      - ../UAV_measurement_data:/workspace/UAV_measurement_data
    # command:
    #   - bin/bash



